### PR TITLE
Code improvements on UI Export

### PR DESCRIPTION
**Pull request by stefandoorn**
@solutionDrive-Alt Made some adjustments while going through the Export code. Mainly some polishing and some small interface return type changes. PR is against your branch in this repo.

### CODE REVIEW

**Comment by lsmith77** [comment]
please rebase on master

**Comment by stefandoorn** [comment]
I'm not sure why this keeps conflicting. The target branch is the exporter branch of @solutionDrive-Alt, not master.

**Comment by lsmith77** [comment]
did you rebase this branch? because I think @solutionDrive-Alt did not yet rebase his

**Comment by stefandoorn** [comment]
Yes but I tried rebasing it to his branch. Maybe @solutionDrive-Alt can simply cherry-pick my commit and see if that works.

**Comment by solutionDrive-Alt** [comment]
I will rebase mine also. Had little time the last days.

**Comment by solutionDrive-Alt** [comment]
Ironically I get also a bunch of conflicts when cherry-picking. But honestly I don't get it, because the conflicts mostly looks like no big deal.

bildschirmfoto 2018-03-08 um 16 41 06

**Comment by solutionDrive-Alt** [comment]
Now the conflicts are gone, but what I absolutely don't get is, why the ExportDataController is shown as complete new file, because this file is there for sure...

https://github.com/FriendsOfSylius/SyliusImportExportPlugin/tree/add-exporter-for-ui/src/Controller

Same for ExportType
https://github.com/FriendsOfSylius/SyliusImportExportPlugin/tree/add-exporter-for-ui/src/Form

**Pull request closed without merging**
