### PR TITLE
Code cleanup (PHP7.1, PHPStan, ECS) 

### PR DESCRIPTION
**Pull request by oallain**
Hello,

To complete the PR https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/179, here is a small PR to fix the types of returns.

### CODE REVIEW

**Comment by oallain** [comment]
Hello,

It's not related specifically to #179 , but it's a PR to clean like this one :)

I don't have sufficient rights to commit on the other PR, so I have create a new one ;)

**Comment by lsmith77** [comment]
you can pull those commits and push them into your branch .. 
if you are unsure how to do this, PM me on slack and I will help you, ok?

**Comment by oallain** [comment]
Hello @lsmith77 ,

I had do that, now i can fix it :smile:

**Comment by lsmith77** [comment]
perfect!

**Comment by stefandoorn** [comment]
Can't we just merge #179 first and then have a cleaner PR to review?

**Comment by lsmith77** [comment]
that would give us a broken build. imho its better to work through those issues in a branch.

**Comment by stefandoorn** [comment]
Yeah, I missed that that one didn't work :(

**Comment by oallain** [comment]
Everything is fixed :smile: 

I think, we can decline #179, all commits are in this PR.

So, i can change PR title too :stuck_out_tongue:

**Comment by lsmith77** [comment]
since you added those commits into this PR, #179 will be automatically closed as merged once we merge this PR.

**Comment by oallain** [comment]
Yeah, I forgot that ;)

**Comment by oallain** [comment]
Hum, i don't understand what Scrutinize says :disappointed:

**Comment by lsmith77** [comment]
I think scrutinizer just had some internal issue and timed out .. lets see if it works this time.

**Comment by oallain** [comment]
:crossed_fingers:

**Comment by lsmith77** [comment]
after retriggering half a dozen times .. it finally passed.

**Comment by oallain** [comment]
Thanks you @lsmith77 ! :party:

**Pull request merged**
