### PR TITLE
Add friends-of-behat/page-object-extension to dev dependencies

### PR DESCRIPTION
**Pull request by stefandoorn**

### CODE REVIEW

**Comment by lsmith77** [comment]
hmm why is it still failing?

**Comment by solutionDrive-Alt** [comment]
It fails because of `CountriesContext` see #161 https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/161/files#diff-aa1be1407728e1c8cf757c1bea4f09c3L11

**Comment by stefandoorn** [comment]
Solved 🎉

**Comment by lsmith77** [comment]
thx!

**Pull request merged**
