### PR TITLE
WIP: Added product processor with taxon for import

### PR DESCRIPTION
**Pull request by redGorillaz**
- Added `src/Processor/ProductProcessor.php`
 - Added `products.csv`
 - modified `src/Ressources/config/service.yml`
 - modified `src/Ressources/config/service_csv.yml`

Did not add test for excel format but should be approximately the same
In the `ProductPrecessor.php`, trying to add taxon with import of products but not working.

### CODE REVIEW

**Comment by lsmith77** [comment]
taken from slack:

```
When i try to import product with taxon I have this mistake 
`Expected argument of type "Sylius\Component\Core\Model\TaxonInterface or be null", "string" given`
```

On what line does this error occur? I don’t see where you set the Taxon on the product, so I wonder what is raising this error.

**Comment by lsmith77** [comment]
Also what is in your custom factories? Does it work with the standard factories?

**Comment by alexispitchen** [comment]
I've made a few changes since then. I've got a simple error now 
```
An exception occurred while executing 'INSERT INTO sylius_taxon_translation (name, slug, description, locale, translatable_id) VALUES (?, ?, ?, ?, ?)' with params ["", null, null, "en_US", 9]:                                  
                                                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'slug' cannot be null
```
And if you look in `services.yml` I use the custom factory for both product and taxon

**Comment by solutionDrive-Alt** [comment]
Thx for your PR. I will try to have a look at your branch this evening.

**Comment by solutionDrive-Alt** [comment]
@alexispitchen I just checked out your code and tested the Import via the backend. I also got the error you mentioned, but when I checked the database I saw that the products were created. So I hat a look at you Import-File and recognized the blank line at the end of it and checked the other files, where the last line is no blank one. So I think the problem is, that our importer till now is not able to handle files with a blank line at the end. I will open a new Issue for that, when you can confirm that this is the problem and it works.

**Comment by oallain** [comment]
@alexispitchen will you continue this feature?
If no, i'll try to do it ;)

**Comment by oallain** [comment]
Hi,

No response on it, so i'll try to do it ;) I need it to my own project.

**Comment by vasilvestre** [comment]
Should be closed, oallain made it :)

**Comment by oallain** [comment]
Yes, I close it.

Thanks

**Pull request closed without merging**
