### PR TITLE
Define import command as a service (closes #52)

### LINKED ISSUE #52: make commands services
https://symfony.com/doc/current/console/commands_as_services.html

### PR DESCRIPTION
**Pull request by stefandoorn**

### CODE REVIEW

**Comment by lsmith77** [comment]
please rebase on master

**Comment by stefandoorn** [comment]
Rebased!

**Comment by lsmith77** [comment]
behat tests need some adjustments.

**Comment by stefandoorn** [comment]
Same CI issue again now as Symfony 3.4.6 got released..

**Comment by lsmith77** [comment]
sigh .. I guess we need to make the conflict something like `^3.4.5`

**Comment by stefandoorn** [comment]
Added PR to ignore 3.4.6 for now, hopefully fixed soon.

**Comment by lsmith77** [comment]
I opened https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/76 setting a range

**Comment by stefandoorn** [comment]
Rebased on master.

**Comment by stefandoorn** [comment]
Finally, it's passing 🎉

**Comment by lsmith77** [comment]
niceeeeeee

**Pull request merged**
