### PR TITLE
travis - add Sylius 1.6

### PR DESCRIPTION
**Pull request by oallain**

### CODE REVIEW

**Comment by oallain** [comment]
Scrutinizer is always wrong, do you think we have to disable it? @stefandoorn @lsmith77

**Comment by stefandoorn** [comment]
It seems to have issues with the amount of dependencies. Maybe we should exclude some or maybe we can even exclude that whole step? Alternative is to remove Scrutinizer, as we have some other quality tools already.

**Comment by oallain** [comment]
> It seems to have issues with the amount of dependencies. Maybe we should exclude some or maybe we can even exclude that whole step? Alternative is to remove Scrutinizer, as we have some other quality tools already.

I think we can remove scrutinizer too. But I haven't the right now 😔

**Comment by lsmith77** [comment]
fine for me .. BTW as you may have noticed, I am really not able to out time into Sylius let alone this Bundle :-/

**Pull request merged**
